# Name : Naveen Kumar Meena
# Roll NO : UE208066

In [1]:
import numpy as np
# Define input
X = np.array([[0,0],[0,1],[1,0],[1,1]])
print(X.shape)
X

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [2]:
#Define output features
Y = np.array([[0,1,1,1]])
# Reshape target into vector
Y = Y.reshape(4,1)
print(Y.shape)
Y

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [3]:
# Select random weights w1, w2
W = np.array([[0.1],[0.2]])
# bias b
b = 0.3
# learning rate alpha
alpha = 0.05
print(W.shape)
W

(2, 1)


array([[0.1],
       [0.2]])

In [5]:
# Sigmoid function
def sigmoid(z):
    sig = 1/(1 + np.exp(-z))
    return sig

In [6]:
# Derivative of sigmoid
def sigmoid_der(z):
    sig_der = sigmoid(z)*(1-sigmoid(z))
    return sig_der

In [9]:
# Neural network
for epoch in range(1000):
# Feedforward network
    z1 = np.dot(X,W)+b
    a1 = sigmoid(z1)
# backpropagation algorithm
# Error calculation
    error = a1 -Y
    l= error.sum()
# derivative calculation
    da2 = error
# dE/da2
    dz2 = sigmoid_der(z1)
#da2/dz2
    deriv = da2 * dz2
# dE/da2 * da2/dz2 = dE/dz2
    X_T = X.T
    dw2 = np.dot(X_T,deriv)
# dE/dw
# updating weight
    W-= alpha * dw2
# updating bias
    for i in deriv:
        b-= alpha*i

In [10]:
print(W)
print(b)

[[2.39311258]
 [2.40156636]]
[-0.82766565]


In [11]:
# prediction for 1 or 0 , target = 1
single_point = np.array([1,0])
# 1st step
result1 = np.dot(single_point,W)+b
# 2nd step
result2 = sigmoid(result1)
print(result2)

[0.82713356]


# Assignment 1

In [12]:
#Predict for (1,1) and target=1
single_point = np.array([1,1])
# 1st step
result1 = np.dot(single_point,W)+b
#2nd step
result2 = sigmoid(result1)
print(result2)

[0.9814218]


In [13]:
#Predict for (0,0) and target=1
single_point = np.array([0,0])
# 1st step
result1 = np.dot(single_point,W)+b
#2nd step
result2 = sigmoid(result1)
print(result2)

[0.30413888]


# Checking Virus contractions using neural networks

In [15]:
import numpy as np
# Define input
X = np.array([[1,0,0,1], [1,0,0,0], [0,0,1,1], [0,1,0,0], [1,1,0,0], [0,0,1,1], [0,0,0,1],[0, 0, 1, 0]])
print(X.shape)
X

(8, 4)


array([[1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [26]:
# Define output features
Y = np.array([[1,1,0,0,1,1,0,0]])
#Reshape target into vector
Y=Y.reshape(8,1)
print(Y.shape)
Y

(8, 1)


array([[1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0]])

In [27]:
# Select random weights w1, w2
W = np.array([[0.1],[0.2],[0.3],[0.4]])
#bias b
b= 0.3
# learning rate alpha 
alpha = 0.05
print(W.shape)
W

(4, 1)


array([[0.1],
       [0.2],
       [0.3],
       [0.4]])

In [28]:
# Neural network
for epoch in range(1000):
# Feedforward network
    z1 = np.dot(X,W)+b
    a1 = sigmoid(z1)
# backpropagation algorithm
# Error calculation
    error = a1 -Y
    l= error.sum()
# derivative calculation
    da2 = error
# dE/da2
    dz2 = sigmoid_der(z1)
#da2/dz2
    deriv = da2 * dz2
# dE/da2 * da2/dz2 = dE/dz2
    X_T = X.T
    dw2 = np.dot(X_T,deriv)
# dE/dw
# updating weight
    W-= alpha * dw2
# updating bias
    for i in deriv:
        b-= alpha*i

In [29]:
print(W)
print(b)

[[ 3.87716459]
 [-0.33622761]
 [ 0.5253264 ]
 [ 0.63647813]]
[-1.67533041]


In [30]:
# prediction for 1,0,0,1 , target = 1
single_point = np.array([1,0,0,1])
# 1st step
result1 = np.dot(single_point,W)+b
# 2nd step
result2 = sigmoid(result1)
print(result2)

[0.94471138]


# Assignment 2

In [35]:
# prediction for 1,0,0,1 , target = 1
single_point = np.array([1,0,1,0])
# 1st step
result1 = np.dot(single_point,W)+b
# 2nd step
result2 = sigmoid(result1)
print(result2)

[0.93861043]


In [32]:
import numpy as np

# Define input
X = np.array([[1,0,0,1], [1,0,0,0], [0,0,1,1], [0,1,0,0], [1,1,0,0], [0,0,1,1], [0,0,0,1],[0, 0, 1, 0]])
print(X.shape)
X

# Define output features
Y = np.array([[1,1,0,0,1,1,0,0]])

#Reshape target into vector
Y=Y.reshape(8,1)
print(Y.shape)
Y

# Select random weights w1, w2
W = np.array([[0.1],[0.2],[0.3],[0.4]])

#bias b
b= 0.3

# learning rate alpha 
alpha = 0.05
print(W.shape)
W

# sigmoid function and its derivative
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

# Neural network
for epoch in range(1000):
    # Feedforward network
    z1 = np.dot(X,W)+b
    a1 = sigmoid(z1)

    # backpropagation algorithm
    # Error calculation
    error = a1 - Y
    l= error.sum()

    # derivative calculation
    da2 = error
    # dE/da2
    dz2 = sigmoid_der(z1)
    #da2/dz2
    deriv = da2 * dz2
    # dE/da2 * da2/dz2 = dE/dz2
    X_T = X.T
    dw2 = np.dot(X_T,deriv)
    # dE/dw
    # updating weight
    W-= alpha * dw2
    # updating bias
    for i in deriv:
        b-= alpha*i

# predicting the output for [0,0,0,1]
input_data = np.array([0,0,0,1])
output = sigmoid(np.dot(input_data, W)+b)
print(output)


(8, 4)
(8, 1)
(4, 1)
[0.26137151]


In [37]:
# prediction for 0,0,1,0 , target = 0
input_data = np.array([0,0,1,0])
output = sigmoid(np.dot(input_data, W)+b)
print(output)

[0.24048835]


# Gates

In [41]:
# OR gate

import numpy as np
# Define input
X = np.array([[0,0],[0,1],[1,0],[1,1]])
#Define output features
Y = np.array([[0,1,1,1]])
# Reshape target into vector
Y = Y.reshape(4,1)
# Select random weights w1, w2
W = np.array([[10],[10]])
# bias b
b = -5

z = np.dot(X,W)+b
sig = 1/(1 + np.exp(-z))
print('Sigmoid \n:', sig)
yhat1 = 0
yhat = []
for i in range(len(Y)):
    if (sig[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhat.append(yhat1)
print('\n Yhat:', yhat)

Sigmoid 
: [[0.00669285]
 [0.99330715]
 [0.99330715]
 [0.99999969]]

 Yhat: [0, 1, 1, 1]


In [43]:
# AND gate
import numpy as np
# Define input
X = np.array([[0,0],[0,1],[1,0],[1,1]])
#Define output features
Y = np.array([[0,0,0,1]])
# Reshape target into vector
Y = Y.reshape(4,1)
# Select random weights w1, w2
W = np.array([[5],[5]])
# bias b
b = -10

z = np.dot(X,W)+b
sig = 1/(1 + np.exp(-z))
print('Sigmoid \n:', sig)
yhat1 = 0
yhat = []
for i in range(len(Y)):
    if (sig[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhat.append(yhat1)
print('\n Yhat:', yhat)

Sigmoid 
: [[4.53978687e-05]
 [6.69285092e-03]
 [6.69285092e-03]
 [5.00000000e-01]]

 Yhat: [0, 0, 0, 1]


In [45]:
# Not gate
import numpy as np
# Define input
X = np.array([[0],[1]])
#Define output features
Y = np.array([[1,0]])
# Reshape target into vector
Y = Y.reshape(2,1)
# Select random weights w1, w2
W_not = -10
# bias b
b_not = 5
z_not = np.dot(X,W_not)+b_not
sig_not = 1/(1 + np.exp(-z_not))
print('Sigmoid \n:', sig_not)
yhat1 = 0
yhat_not = []
for i in range(len(Y)):
    if (sig_not[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhat_not.append(yhat1)
print('\n Yhat:', yhat_not)

Sigmoid 
: [[0.99330715]
 [0.00669285]]

 Yhat: [1, 0]


In [67]:
# Define input
X = np.array([[0,0],[0,1],[1,0],[1,1]])

# Define output features
Y = np.array([[1,0,0,1]])

# Reshape target into vector
Y = Y.reshape(4,1)

# Layer 1: (Not X1) and (Not X2) gate (NOR gate)
W11 = np.array([[-15],[-15]])
b11 = 12

# Apply weights and bias
z11 = np.dot(X, W11) + b11

# Apply activation function (sigmoid)
sig11 = 1 / (1 + np.exp(-z11))

print(sig11)
# Output
yhat1 = 0
yhata1 = []
for i in range(len(Y)):
    if (sig11[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhata1.append(yhat1)
print('\n Yhat:', yhata1)


[[9.99993856e-01]
 [4.74258732e-02]
 [4.74258732e-02]
 [1.52299795e-08]]

 Yhat: [1, 0, 0, 0]


In [62]:
# Define input
X = np.array([[0,0],[0,1],[1,0],[1,1]])

# Define output features
Y = np.array([[1,0,0,1]])

# Reshape target into vector
Y = Y.reshape(4,1)

# Layer 1: (Not X1) and (Not X2) gate (NOR gate)
W11 = np.array([[15],[15]])
b11 = -25

# Apply weights and bias
z11 = np.dot(X, W11) + b11

# Apply activation function (sigmoid)
sig11 = 1 / (1 + np.exp(-z11))

print(sig11)
# Output
yhat1 = 0
yhata2 = []
for i in range(len(Y)):
    if (sig11[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhata2.append(yhat1)
print('\n Yhat:', yhat)

[[1.38879439e-11]
 [4.53978687e-05]
 [4.53978687e-05]
 [9.93307149e-01]]

 Yhat: [0, 0, 0, 1]


In [63]:

w21=20
w22=20
b2=-15
z1=np.dot(w21,yhata1)
z2=np.dot(w22,yhata2)
z=z1+z2+b
print(z)
sig=1/(1+np.exp(-z))
print('Sigmoid \n:', sig)
yhat1 = 0
yhatf = []
for i in range(len(Y)):
    if (sig[i] < 0.5):
        yhat1 = 0
    else:
        yhat1 = 1
    yhatf.append(yhat1)
print('\n Yhata2:', yhatf)

[ 10 -10 -10  10]
Sigmoid 
: [9.99954602e-01 4.53978687e-05 4.53978687e-05 9.99954602e-01]

 Yhata2: [1, 0, 0, 1]
